parameters:
#    scops_bague.example.class: Scops\BagueBundle\Example

services:
#    scops_bague.example:
#        class: %scops_bague.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
