pnpc_cistude_europe:
    resource: "@PnpcCistudeEuropeBundle/Resources/config/routing.yml"
    prefix:   /CistudeEurope

pnpc_tortue_hermann:
    resource: "@PnpcTortueHermannBundle/Resources/config/routing.yml"
    prefix:   /TortueHermann

pnpc_scops:
    resource: "@PnpcScopsBundle/Resources/config/routing.yml"
    prefix:   /Scops

# _acme_demo:
    # resource: "@AcmeDemoBundle/Resources/config/routing.yml"

accueil:
    pattern:  /
    defaults: {_controller:PnpcUserBundle:Security:login}

# login_check:
    # pattern:  /login_check

# logout:
    # pattern:  /logout
    # defaults: {_controller:PnpcUserBundle:User:logout}

AvroCsvBundle:
    resource: "@AvroCsvBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@PnpcUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
