#pnpc_scops_homepag:
    #pattern:  /
    #defaults: { _controller: PnpcScopsBundle:Scops:index}

pnpc_scops_homepage:
    pattern:  /
    defaults: { _controller: PnpcScopsBundle:Scops:index}

pnpc_scops_voir:
    pattern:      /liste/
    defaults:  { _controller: PnpcScopsBundle:Scops:voir }

pnpc_scops_voirplus:
    pattern:      /liste/{id}
    defaults:  { _controller: PnpcScopsBundle:Scops:voirplus }
    requirements:
        id:  \d+

pnpc_scops_ajouter:
    pattern:      /ajouter
    defaults:  { _controller: PnpcScopsBundle:Scops:ajouter }

pnpc_scops_modifier:
    pattern:      /modifier/{id}
    defaults:  { _controller: PnpcScopsBundle:Scops:modifier }
    requirements:
        id:  \d+

pnpc_scops_supprimer:
    pattern:      /supprimer/{id}
    defaults:  { _controller: PnpcScopsBundle:Scops:supprimer }
    requirements:
        id:  \d+

pnpc_scops_supprimerdoc:
    pattern:      /supprimerdoc/{id}
    defaults:  { _controller: PnpcScopsBundle:Scops:supprimerdoc }
    requirements:
        id:  \d+

pnpc_scops_diapo:
    pattern:      /photos/
    defaults:  { _controller: PnpcScopsBundle:Scops:photo }

pnpc_scops_doc:
    pattern:      /documents/
    defaults:  { _controller: PnpcScopsBundle:Scops:doc }

pnpc_scops_upload:
    pattern:      /documents/upload
    defaults:  { _controller: PnpcScopsBundle:Scops:upload }

pnpc_scops_uploadImage:
    pattern:      /photos/upload
    defaults:  { _controller: PnpcScopsBundle:Scops:uploadImage }

pnpc_scops_request_form:
    pattern: /liste/request_form
    defaults: {_controller: PnpcScopsBundle:Scops:searchform}

pnpc_scops_request_result:
    pattern: /liste/request_result
    defaults: {_controller: PnpcScopsBundle:Scops:requete}

