<?php

namespace Proxies\__CG__\Pnpc\Bundle\CistudeEuropeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Infos extends \Pnpc\Bundle\CistudeEuropeBundle\Entity\Infos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'pays', 'codeInsee', 'localite', 'lieudit', 'date', 'protocole', 'temperature', 'nebulosite', 'precipitation', 'vent', 'visibilite', 'autre', 'site', 'modeCapture', 'action', 'numPiege', 'latWgs84', 'longWgs84', 'numSession', 'heureObservation', 'observateur1', 'observateur2', 'espece', 'codeMarquage', 'numMarquage', 'longueurDossiere', 'largeurDossiere', 'hauteurCarapace', 'longueurPlastron', 'largeurAvantPlastron', 'largeurArrierePlastron', 'striesVisibles', 'nombreStries', 'poids', 'stade', 'sexe', 'couleurYeux', 'couleurGeneraleDossiere', 'ptsTraitsJaunesDossiere', 'couleurGeneralePlastron', 'tachesPtsPlastron', 'corpsRepartDensitePtsTraits', 'corpsSignesParticuliers', 'tracesBlessures', 'observations');
        }

        return array('__isInitialized__', 'id', 'pays', 'codeInsee', 'localite', 'lieudit', 'date', 'protocole', 'temperature', 'nebulosite', 'precipitation', 'vent', 'visibilite', 'autre', 'site', 'modeCapture', 'action', 'numPiege', 'latWgs84', 'longWgs84', 'numSession', 'heureObservation', 'observateur1', 'observateur2', 'espece', 'codeMarquage', 'numMarquage', 'longueurDossiere', 'largeurDossiere', 'hauteurCarapace', 'longueurPlastron', 'largeurAvantPlastron', 'largeurArrierePlastron', 'striesVisibles', 'nombreStries', 'poids', 'stade', 'sexe', 'couleurYeux', 'couleurGeneraleDossiere', 'ptsTraitsJaunesDossiere', 'couleurGeneralePlastron', 'tachesPtsPlastron', 'corpsRepartDensitePtsTraits', 'corpsSignesParticuliers', 'tracesBlessures', 'observations');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Infos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays($pays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', array($pays));

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', array());

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeInsee($codeInsee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeInsee', array($codeInsee));

        return parent::setCodeInsee($codeInsee);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeInsee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeInsee', array());

        return parent::getCodeInsee();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalite($localite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalite', array($localite));

        return parent::setLocalite($localite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalite', array());

        return parent::getLocalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieudit($lieudit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieudit', array($lieudit));

        return parent::setLieudit($lieudit);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieudit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieudit', array());

        return parent::getLieudit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setProtocole($protocole)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProtocole', array($protocole));

        return parent::setProtocole($protocole);
    }

    /**
     * {@inheritDoc}
     */
    public function getProtocole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtocole', array());

        return parent::getProtocole();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemperature($temperature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemperature', array($temperature));

        return parent::setTemperature($temperature);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemperature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemperature', array());

        return parent::getTemperature();
    }

    /**
     * {@inheritDoc}
     */
    public function setNebulosite($nebulosite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNebulosite', array($nebulosite));

        return parent::setNebulosite($nebulosite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNebulosite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNebulosite', array());

        return parent::getNebulosite();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecipitation($precipitation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecipitation', array($precipitation));

        return parent::setPrecipitation($precipitation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecipitation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecipitation', array());

        return parent::getPrecipitation();
    }

    /**
     * {@inheritDoc}
     */
    public function setVent($vent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVent', array($vent));

        return parent::setVent($vent);
    }

    /**
     * {@inheritDoc}
     */
    public function getVent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVent', array());

        return parent::getVent();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisibilite($visibilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisibilite', array($visibilite));

        return parent::setVisibilite($visibilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisibilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisibilite', array());

        return parent::getVisibilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutre($autre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutre', array($autre));

        return parent::setAutre($autre);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutre', array());

        return parent::getAutre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite($site)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', array($site));

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', array());

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setModeCapture($modeCapture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModeCapture', array($modeCapture));

        return parent::setModeCapture($modeCapture);
    }

    /**
     * {@inheritDoc}
     */
    public function getModeCapture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeCapture', array());

        return parent::getModeCapture();
    }

    /**
     * {@inheritDoc}
     */
    public function setAction($action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAction', array($action));

        return parent::setAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', array());

        return parent::getAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumPiege($numPiege)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumPiege', array($numPiege));

        return parent::setNumPiege($numPiege);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumPiege()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumPiege', array());

        return parent::getNumPiege();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatWgs84($latWgs84)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatWgs84', array($latWgs84));

        return parent::setLatWgs84($latWgs84);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatWgs84()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatWgs84', array());

        return parent::getLatWgs84();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongWgs84($longWgs84)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongWgs84', array($longWgs84));

        return parent::setLongWgs84($longWgs84);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongWgs84()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongWgs84', array());

        return parent::getLongWgs84();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSession($numSession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSession', array($numSession));

        return parent::setNumSession($numSession);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSession', array());

        return parent::getNumSession();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureObservation($heureObservation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureObservation', array($heureObservation));

        return parent::setHeureObservation($heureObservation);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureObservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureObservation', array());

        return parent::getHeureObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservateur1($observateur1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservateur1', array($observateur1));

        return parent::setObservateur1($observateur1);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservateur1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservateur1', array());

        return parent::getObservateur1();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservateur2($observateur2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservateur2', array($observateur2));

        return parent::setObservateur2($observateur2);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservateur2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservateur2', array());

        return parent::getObservateur2();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspece($espece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspece', array($espece));

        return parent::setEspece($espece);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspece', array());

        return parent::getEspece();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeMarquage($codeMarquage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeMarquage', array($codeMarquage));

        return parent::setCodeMarquage($codeMarquage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeMarquage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeMarquage', array());

        return parent::getCodeMarquage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumMarquage($numMarquage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumMarquage', array($numMarquage));

        return parent::setNumMarquage($numMarquage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumMarquage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumMarquage', array());

        return parent::getNumMarquage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongueurDossiere($longueurDossiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongueurDossiere', array($longueurDossiere));

        return parent::setLongueurDossiere($longueurDossiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongueurDossiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongueurDossiere', array());

        return parent::getLongueurDossiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setLargeurDossiere($largeurDossiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLargeurDossiere', array($largeurDossiere));

        return parent::setLargeurDossiere($largeurDossiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getLargeurDossiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLargeurDossiere', array());

        return parent::getLargeurDossiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setHauteurCarapace($hauteurCarapace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHauteurCarapace', array($hauteurCarapace));

        return parent::setHauteurCarapace($hauteurCarapace);
    }

    /**
     * {@inheritDoc}
     */
    public function getHauteurCarapace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHauteurCarapace', array());

        return parent::getHauteurCarapace();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongueurPlastron($longueurPlastron)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongueurPlastron', array($longueurPlastron));

        return parent::setLongueurPlastron($longueurPlastron);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongueurPlastron()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongueurPlastron', array());

        return parent::getLongueurPlastron();
    }

    /**
     * {@inheritDoc}
     */
    public function setLargeurAvantPlastron($largeurAvantPlastron)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLargeurAvantPlastron', array($largeurAvantPlastron));

        return parent::setLargeurAvantPlastron($largeurAvantPlastron);
    }

    /**
     * {@inheritDoc}
     */
    public function getLargeurAvantPlastron()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLargeurAvantPlastron', array());

        return parent::getLargeurAvantPlastron();
    }

    /**
     * {@inheritDoc}
     */
    public function setLargeurArrierePlastron($largeurArrierePlastron)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLargeurArrierePlastron', array($largeurArrierePlastron));

        return parent::setLargeurArrierePlastron($largeurArrierePlastron);
    }

    /**
     * {@inheritDoc}
     */
    public function getLargeurArrierePlastron()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLargeurArrierePlastron', array());

        return parent::getLargeurArrierePlastron();
    }

    /**
     * {@inheritDoc}
     */
    public function setStriesVisibles($striesVisibles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStriesVisibles', array($striesVisibles));

        return parent::setStriesVisibles($striesVisibles);
    }

    /**
     * {@inheritDoc}
     */
    public function getStriesVisibles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStriesVisibles', array());

        return parent::getStriesVisibles();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreStries($nombreStries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreStries', array($nombreStries));

        return parent::setNombreStries($nombreStries);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreStries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreStries', array());

        return parent::getNombreStries();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoids($poids)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoids', array($poids));

        return parent::setPoids($poids);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoids()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoids', array());

        return parent::getPoids();
    }

    /**
     * {@inheritDoc}
     */
    public function setStade($stade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStade', array($stade));

        return parent::setStade($stade);
    }

    /**
     * {@inheritDoc}
     */
    public function getStade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStade', array());

        return parent::getStade();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', array($sexe));

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', array());

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouleurYeux($couleurYeux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouleurYeux', array($couleurYeux));

        return parent::setCouleurYeux($couleurYeux);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouleurYeux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouleurYeux', array());

        return parent::getCouleurYeux();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouleurGeneraleDossiere($couleurGeneraleDossiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouleurGeneraleDossiere', array($couleurGeneraleDossiere));

        return parent::setCouleurGeneraleDossiere($couleurGeneraleDossiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouleurGeneraleDossiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouleurGeneraleDossiere', array());

        return parent::getCouleurGeneraleDossiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setPtsTraitsJaunesDossiere($ptsTraitsJaunesDossiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPtsTraitsJaunesDossiere', array($ptsTraitsJaunesDossiere));

        return parent::setPtsTraitsJaunesDossiere($ptsTraitsJaunesDossiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getPtsTraitsJaunesDossiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPtsTraitsJaunesDossiere', array());

        return parent::getPtsTraitsJaunesDossiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouleurGeneralePlastron($couleurGeneralePlastron)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouleurGeneralePlastron', array($couleurGeneralePlastron));

        return parent::setCouleurGeneralePlastron($couleurGeneralePlastron);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouleurGeneralePlastron()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouleurGeneralePlastron', array());

        return parent::getCouleurGeneralePlastron();
    }

    /**
     * {@inheritDoc}
     */
    public function setTachesPtsPlastron($tachesPtsPlastron)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTachesPtsPlastron', array($tachesPtsPlastron));

        return parent::setTachesPtsPlastron($tachesPtsPlastron);
    }

    /**
     * {@inheritDoc}
     */
    public function getTachesPtsPlastron()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTachesPtsPlastron', array());

        return parent::getTachesPtsPlastron();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorpsRepartDensitePtsTraits($corpsRepartDensitePtsTraits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorpsRepartDensitePtsTraits', array($corpsRepartDensitePtsTraits));

        return parent::setCorpsRepartDensitePtsTraits($corpsRepartDensitePtsTraits);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorpsRepartDensitePtsTraits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorpsRepartDensitePtsTraits', array());

        return parent::getCorpsRepartDensitePtsTraits();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorpsSignesParticuliers($corpsSignesParticuliers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorpsSignesParticuliers', array($corpsSignesParticuliers));

        return parent::setCorpsSignesParticuliers($corpsSignesParticuliers);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorpsSignesParticuliers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorpsSignesParticuliers', array());

        return parent::getCorpsSignesParticuliers();
    }

    /**
     * {@inheritDoc}
     */
    public function setTracesBlessures($tracesBlessures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTracesBlessures', array($tracesBlessures));

        return parent::setTracesBlessures($tracesBlessures);
    }

    /**
     * {@inheritDoc}
     */
    public function getTracesBlessures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTracesBlessures', array());

        return parent::getTracesBlessures();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservations($observations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservations', array($observations));

        return parent::setObservations($observations);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservations', array());

        return parent::getObservations();
    }

}
