<?php

namespace Proxies\__CG__\Pnpc\Bundle\ScopsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Info extends \Pnpc\Bundle\ScopsBundle\Entity\Info implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'numero', 'theme', 'bagueur', 'pays', 'dept', 'localite', 'annee', 'num_semaine', 'date', 'lieudit', 'fs', 'hs', 'ds', 'heure', 'action', 'centre', 'bague', 'circ_repr', 'cond_repr', 'nom_scientifique', 'nom_vernaculaire', 'espece', 'sexe', 'age', 'lp', 'ad', 'ma', 'memo', 'secteur', 'bg', 'cs', 'pc', 'pi', 'mu', 'es', 'nf', 'sg', 're', 'rr', 'ge', 'lat', 'lon', 'fi', 'fg', 'fd', 'classe', 'tl', 'lt', 'bp', 'tq', 'cr', 'x1', 'x2');
        }

        return array('__isInitialized__', 'id', 'numero', 'theme', 'bagueur', 'pays', 'dept', 'localite', 'annee', 'num_semaine', 'date', 'lieudit', 'fs', 'hs', 'ds', 'heure', 'action', 'centre', 'bague', 'circ_repr', 'cond_repr', 'nom_scientifique', 'nom_vernaculaire', 'espece', 'sexe', 'age', 'lp', 'ad', 'ma', 'memo', 'secteur', 'bg', 'cs', 'pc', 'pi', 'mu', 'es', 'nf', 'sg', 're', 'rr', 'ge', 'lat', 'lon', 'fi', 'fg', 'fd', 'classe', 'tl', 'lt', 'bp', 'tq', 'cr', 'x1', 'x2');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Info $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setTheme($theme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTheme', array($theme));

        return parent::setTheme($theme);
    }

    /**
     * {@inheritDoc}
     */
    public function getTheme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTheme', array());

        return parent::getTheme();
    }

    /**
     * {@inheritDoc}
     */
    public function setBagueur($bagueur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBagueur', array($bagueur));

        return parent::setBagueur($bagueur);
    }

    /**
     * {@inheritDoc}
     */
    public function getBagueur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBagueur', array());

        return parent::getBagueur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays($pays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', array($pays));

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', array());

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setDept($dept)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDept', array($dept));

        return parent::setDept($dept);
    }

    /**
     * {@inheritDoc}
     */
    public function getDept()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDept', array());

        return parent::getDept();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalite($localite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalite', array($localite));

        return parent::setLocalite($localite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalite', array());

        return parent::getLocalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee($annee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', array($annee));

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', array());

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSemaine($num_semaine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSemaine', array($num_semaine));

        return parent::setNumSemaine($num_semaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSemaine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSemaine', array());

        return parent::getNumSemaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieudit($lieudit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieudit', array($lieudit));

        return parent::setLieudit($lieudit);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieudit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieudit', array());

        return parent::getLieudit();
    }

    /**
     * {@inheritDoc}
     */
    public function setFs($fs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFs', array($fs));

        return parent::setFs($fs);
    }

    /**
     * {@inheritDoc}
     */
    public function getFs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFs', array());

        return parent::getFs();
    }

    /**
     * {@inheritDoc}
     */
    public function setHs($hs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHs', array($hs));

        return parent::setHs($hs);
    }

    /**
     * {@inheritDoc}
     */
    public function getHs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHs', array());

        return parent::getHs();
    }

    /**
     * {@inheritDoc}
     */
    public function setDs($ds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDs', array($ds));

        return parent::setDs($ds);
    }

    /**
     * {@inheritDoc}
     */
    public function getDs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDs', array());

        return parent::getDs();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeure($heure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeure', array($heure));

        return parent::setHeure($heure);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeure', array());

        return parent::getHeure();
    }

    /**
     * {@inheritDoc}
     */
    public function setAction($action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAction', array($action));

        return parent::setAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', array());

        return parent::getAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentre($centre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentre', array($centre));

        return parent::setCentre($centre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentre', array());

        return parent::getCentre();
    }

    /**
     * {@inheritDoc}
     */
    public function setBague($bague)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBague', array($bague));

        return parent::setBague($bague);
    }

    /**
     * {@inheritDoc}
     */
    public function getBague()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBague', array());

        return parent::getBague();
    }

    /**
     * {@inheritDoc}
     */
    public function setCircRepr($circRepr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCircRepr', array($circRepr));

        return parent::setCircRepr($circRepr);
    }

    /**
     * {@inheritDoc}
     */
    public function getCircRepr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCircRepr', array());

        return parent::getCircRepr();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondRepr($cond_repr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondRepr', array($cond_repr));

        return parent::setCondRepr($cond_repr);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondRepr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondRepr', array());

        return parent::getCondRepr();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomScientifique($nomScientifique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomScientifique', array($nomScientifique));

        return parent::setNomScientifique($nomScientifique);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomScientifique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomScientifique', array());

        return parent::getNomScientifique();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomVernaculaire($nomVernaculaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomVernaculaire', array($nomVernaculaire));

        return parent::setNomVernaculaire($nomVernaculaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomVernaculaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomVernaculaire', array());

        return parent::getNomVernaculaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspece($espece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspece', array($espece));

        return parent::setEspece($espece);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspece', array());

        return parent::getEspece();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', array($sexe));

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', array());

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge($age)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', array($age));

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', array());

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setLp($lp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLp', array($lp));

        return parent::setLp($lp);
    }

    /**
     * {@inheritDoc}
     */
    public function getLp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLp', array());

        return parent::getLp();
    }

    /**
     * {@inheritDoc}
     */
    public function setAd($ad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAd', array($ad));

        return parent::setAd($ad);
    }

    /**
     * {@inheritDoc}
     */
    public function getAd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAd', array());

        return parent::getAd();
    }

    /**
     * {@inheritDoc}
     */
    public function setMa($ma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMa', array($ma));

        return parent::setMa($ma);
    }

    /**
     * {@inheritDoc}
     */
    public function getMa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMa', array());

        return parent::getMa();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemo($memo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemo', array($memo));

        return parent::setMemo($memo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemo', array());

        return parent::getMemo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecteur($secteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecteur', array($secteur));

        return parent::setSecteur($secteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecteur', array());

        return parent::getSecteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setBg($bg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBg', array($bg));

        return parent::setBg($bg);
    }

    /**
     * {@inheritDoc}
     */
    public function getBg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBg', array());

        return parent::getBg();
    }

    /**
     * {@inheritDoc}
     */
    public function setCs($cs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCs', array($cs));

        return parent::setCs($cs);
    }

    /**
     * {@inheritDoc}
     */
    public function getCs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCs', array());

        return parent::getCs();
    }

    /**
     * {@inheritDoc}
     */
    public function setPc($pc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPc', array($pc));

        return parent::setPc($pc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPc', array());

        return parent::getPc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPi($pi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPi', array($pi));

        return parent::setPi($pi);
    }

    /**
     * {@inheritDoc}
     */
    public function getPi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPi', array());

        return parent::getPi();
    }

    /**
     * {@inheritDoc}
     */
    public function setMu($mu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMu', array($mu));

        return parent::setMu($mu);
    }

    /**
     * {@inheritDoc}
     */
    public function getMu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMu', array());

        return parent::getMu();
    }

    /**
     * {@inheritDoc}
     */
    public function setEs($es)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEs', array($es));

        return parent::setEs($es);
    }

    /**
     * {@inheritDoc}
     */
    public function getEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEs', array());

        return parent::getEs();
    }

    /**
     * {@inheritDoc}
     */
    public function setNf($nf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNf', array($nf));

        return parent::setNf($nf);
    }

    /**
     * {@inheritDoc}
     */
    public function getNf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNf', array());

        return parent::getNf();
    }

    /**
     * {@inheritDoc}
     */
    public function setSg($sg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSg', array($sg));

        return parent::setSg($sg);
    }

    /**
     * {@inheritDoc}
     */
    public function getSg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSg', array());

        return parent::getSg();
    }

    /**
     * {@inheritDoc}
     */
    public function setRe($re)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRe', array($re));

        return parent::setRe($re);
    }

    /**
     * {@inheritDoc}
     */
    public function getRe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRe', array());

        return parent::getRe();
    }

    /**
     * {@inheritDoc}
     */
    public function setRr($rr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRr', array($rr));

        return parent::setRr($rr);
    }

    /**
     * {@inheritDoc}
     */
    public function getRr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRr', array());

        return parent::getRr();
    }

    /**
     * {@inheritDoc}
     */
    public function setGe($ge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGe', array($ge));

        return parent::setGe($ge);
    }

    /**
     * {@inheritDoc}
     */
    public function getGe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGe', array());

        return parent::getGe();
    }

    /**
     * {@inheritDoc}
     */
    public function setLat($lat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLat', array($lat));

        return parent::setLat($lat);
    }

    /**
     * {@inheritDoc}
     */
    public function getLat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLat', array());

        return parent::getLat();
    }

    /**
     * {@inheritDoc}
     */
    public function setLon($lon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLon', array($lon));

        return parent::setLon($lon);
    }

    /**
     * {@inheritDoc}
     */
    public function getLon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLon', array());

        return parent::getLon();
    }

    /**
     * {@inheritDoc}
     */
    public function setFi($fi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFi', array($fi));

        return parent::setFi($fi);
    }

    /**
     * {@inheritDoc}
     */
    public function getFi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFi', array());

        return parent::getFi();
    }

    /**
     * {@inheritDoc}
     */
    public function setFg($fg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFg', array($fg));

        return parent::setFg($fg);
    }

    /**
     * {@inheritDoc}
     */
    public function getFg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFg', array());

        return parent::getFg();
    }

    /**
     * {@inheritDoc}
     */
    public function setFd($fd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFd', array($fd));

        return parent::setFd($fd);
    }

    /**
     * {@inheritDoc}
     */
    public function getFd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFd', array());

        return parent::getFd();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse($classe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', array($classe));

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', array());

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTl($tl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTl', array($tl));

        return parent::setTl($tl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTl', array());

        return parent::getTl();
    }

    /**
     * {@inheritDoc}
     */
    public function setLt($lt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLt', array($lt));

        return parent::setLt($lt);
    }

    /**
     * {@inheritDoc}
     */
    public function getLt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLt', array());

        return parent::getLt();
    }

    /**
     * {@inheritDoc}
     */
    public function setBp($bp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBp', array($bp));

        return parent::setBp($bp);
    }

    /**
     * {@inheritDoc}
     */
    public function getBp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBp', array());

        return parent::getBp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTq($tq)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTq', array($tq));

        return parent::setTq($tq);
    }

    /**
     * {@inheritDoc}
     */
    public function getTq()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTq', array());

        return parent::getTq();
    }

    /**
     * {@inheritDoc}
     */
    public function setCr($cr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCr', array($cr));

        return parent::setCr($cr);
    }

    /**
     * {@inheritDoc}
     */
    public function getCr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCr', array());

        return parent::getCr();
    }

    /**
     * {@inheritDoc}
     */
    public function setX1($x1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setX1', array($x1));

        return parent::setX1($x1);
    }

    /**
     * {@inheritDoc}
     */
    public function getX1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getX1', array());

        return parent::getX1();
    }

    /**
     * {@inheritDoc}
     */
    public function setX2($x2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setX2', array($x2));

        return parent::setX2($x2);
    }

    /**
     * {@inheritDoc}
     */
    public function getX2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getX2', array());

        return parent::getX2();
    }

}
