<?php

namespace Pnpc\Bundle\ScopsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsRepository extends EntityRepository
{
	public function docContact()
	{
		$requete = $this->_em->createQueryBuilder()
					->select('d')
					->from('PnpcScopsBundle:Documents','d')
					->where('d.type = :contact')
					->getQuery()
					->getResult();
					
		return $requete;				
	}
	public function docBaguage()
	{
		$requete = $this->_em->createQueryBuilder()
					->select('d')
					->from('PnpcScopsBundle:Documents','d')
					->where('d.type = baguage')
					->getQuery()
					->getResult();
					
		return $requete;				
	}
	public function docGestion()
	{
		$requete = $this->_em->createQueryBuilder()
					->select('d')
					->from('PnpcScopsBundle:Documents','d')
					->where('d.type = gestion')
					->getQuery()
					->getResult();
					
		return $requete;				
	}
}
