<?php

namespace Pnpc\Bundle\ScopsBundle\Entity;

use Doctrine\ORM\EntityRepository;
//use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * InfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends EntityRepository
{

	public function VoirTout()
	{
		$requete = $this->createQueryBuilder('i')
					->getQuery()
					->getResult();
		return $requete;
	}
	
	public function VoirUn($id)
	{
		$requete = $this->_em->createQueryBuilder()
					->select('i')
					->from('PnpcScopsBundle:Info','i')
					->where('i.id = :id')
					->setParameter('id',$id)
					->getQuery()
					->getResult();
					
		return $requete;				
	}
	
		public function Supprimer($id)
	{
		$requete = $this->_em->createQueryBuilder()
					->select('i')
					->from('PnpcScopsBundle:Info','i')
					->where('i.id = :id')
					->setParameter('id',$id)
					->getQuery()
					->getResult();
					
		return $requete;				
	}
		public function Modifier($id)
	{
		$requete = $this->_em->createQueryBuilder()
					->select('i')
					->from('PnpcScopsBundle:Info','i')
					->where('i.id = :id')
					->setParameter('id',$id)
					->getQuery()
					->getResult();
					
		return $requete;				
	}
	public function recup()
	{
	$liste = $this->getDoctrine()
                     ->getManager()
                     ->getRepository('PnpcScopsBundle:Info')
					 ->VoirTout();
		
		if (!$liste) 
		{
        throw $this->createNotFoundException('Oups votre base de données est vide!!! ');
		}
		
		foreach($liste as $info)
		{}
	}
	
	public function Recherche($champ,$mot)
	{
		$requete = $this->_em->createQueryBuilder()
					->select('i')
					->from('PnpcScopsBundle:Info','i')
					->where('i.'.$champ.'= :mot')
					->setParameter('mot',$mot)
					->getQuery()
					->getResult();
					
		return $requete;				
	}	
	
}
