parameters:
#    pnpc_cistude_europe.example.class: Pnpc\Bundle\CistudeEuropeBundle\Example

services:
#    pnpc_cistude_europe.example:
#        class: %pnpc_cistude_europe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
